name: Build Executable with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
          echo "C:\Users\runneradmin\.local\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build executable with PyInstaller
        run: |
          poetry run pyinstaller --onefile --name=my_app src/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_app
          path: dist/my_app.exe
