name: Build Executable with PyInstaller

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
          $poetryPath = "$env:APPDATA\Python\Scripts"
          echo "$poetryPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "Poetry installed at $poetryPath"

      - name: Verify Poetry Installation
        run: |
          $env:PATH += ";$env:APPDATA\Python\Scripts"
          poetry --version

      - name: Install dependencies
        run: |
          $env:PATH += ";$env:APPDATA\Python\Scripts"
          poetry install --no-root

      - name: Build executable with PyInstaller
        run: |
          $env:PATH += ";$env:APPDATA\Python\Scripts"
          poetry run pyinstaller --onefile --name=my_app main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_app
          path: dist/my_app.exe
